### ISSUE TITLE
hsl colors are not displaying correctly.

### ISSUE THREAD

**Issue by willsoto** [tulios/css-color-highlight#1]
![screen shot 2014-03-09 at 9 10 39 pm](https://f.cloud.github.com/assets/2791730/2369918/deba6308-a7f0-11e3-9f17-3840d7f41a27.png)

**Comment by tulios** [comment]
Indeed, I'll add the support.

**Comment by willsoto** [comment]
Awesome, thank you. If I have a chance, I'll actually take a look myself and make the PR

**Comment by tulios** [comment]
I have included support to HSL and HSLA to v0.3.0.

Thanks for the issue =)

**Comment by willsoto** [comment]
Thanks for the fix :smile:
